# Step 1: Build
FROM node:18-alpine AS builder

# Install pnpm
RUN npm install -g pnpm

WORKDIR /app
COPY . .

RUN pnpm install
RUN pnpm run build

# Step 2: Serve
FROM nginx:alpine

# Copy build hasil React/Vue ke nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
